--- 
title: "Álgebra Lineal"
author: "Domingo López"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---
```{r echo = FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      results = "asis",
                      message = FALSE,
                      warning = FALSE)

set.seed(1234)
``` 
# Introducción

En este libro vamos a recopilar algunas de las preguntas y dudas más frecuentes en los temas de Álgebra Lineal, con ejemplos resueltos, y acompañados de la teoría necesaria para comprender los resultados.

Cada capítulo incluye preguntas y sus respuestas acerca de aquellos procedimientos más usuales relacionados con el tema correspondiente.
```{r}
library(stringr)
library(tidyverse)
library(glue)
library(fractional)
library(matlab)
library(matlib)
library(pracma)
library(numericoUMA)

glue_latex <- function(...) {
  
  glue::glue("$$",
             ...,
             "$$",
             .open = "[", .close = "]", 
             .sep = "")
  
}

```
